// Begin AutoGenerated Includes - DO NOT EDIT BELOW
#include <GyroPalmEngine.h>
#include <GyroPalmLVGL.h>
// End AutoGenerated Includes - DO NOT EDIT ABOVE

#include <ArduinoJson.h>
#include <WiFi.h>

// Wifi Settings.
const char* ssid = "****WIFI-SSID****";
const char* password = "****WIFI-PASSWORD****";

// Octoprint Settings
String    OCTO_API_KEY = "**********************************";  // Via: OctoPrint > Settings > API
int       OCTO_PORT = 5000;
String    OCTO_HOST = "192.168.0.44";

// Printer status update interval
long interval = 6000; // Every 6 seconds

// Test button for sending g-code commands etc. 
const int buttonPin = 0; // Boot button for now (ESP32 Dev Board (& Wemos Lolin)). Boards without an extra button will need a breadboard etc. 

// status of printer
String printerStatusString = NULL;

// ##### END SETTINGS


//////////////////////////////////////////////////////////////////////////////// 
WiFiClient client;
String ipStr = "";
// Button press detection
int buttonState = 0;
int lastButtonState = HIGH;   // the previous reading from the input pin
// Debounce
unsigned long lastDebounceTime = 0;  // the last time the output pin was toggled
unsigned long debounceDelay = 50;    // the debounce time; increase if the output flickers
// For status request timer.
long previousMillis = 0;    

/////////////////////////////////////////////////////////////////////////////////



// Begin AutoGenerated Globals - DO NOT EDIT BELOW
GyroPalm *device;
GyroPalmEngine gplm("gp123456");    //declares a GyroPalm Engine object with wearableID

AXP20X_Class *power;
lv_task_t *barTask;
void lv_update_task(struct _lv_task_t *);

enum Screen { SCR_HOME, SCR_WATCH };	//Screen indexes
lv_obj_t *screen[2];    //screen pointers
GyroPalmLVGL form[2];   //screen helper methods
Screen curScreen = SCR_HOME;    //default screen
// End AutoGenerated Globals - DO NOT EDIT ABOVE

// Begin AutoGenerated Callbacks - DO NOT EDIT BELOW
void lv_update_task(struct _lv_task_t *data) {
    int battPercent = power->getBattPercentage();
    bool isCharging = power->isChargeing();
    form[curScreen].updateBar(battPercent, isCharging);
    form[curScreen].setTime(gplm.getTime());     //update Time View
}

static void btn_event_handler(lv_obj_t * obj, lv_event_t event)
{
    if (event == LV_EVENT_CLICKED) {
        String btnName = lv_list_get_btn_text(obj);
		Serial.printf("Clicked: %s\n", btnName);

        switch (curScreen)
        {
            case SCR_HOME:
			
            break;

            case SCR_WATCH:
			if (btnName == "HomeXY"){ // homeing

                    // getPrinterState(); 
                    // getTemperatures();
                    goHomeXY();
                    // goHomeXYZ();
                    // goForLevel();
                } 
            break;


            default: break;
		}
	}
}

// End AutoGenerated Callbacks - DO NOT EDIT ABOVE

// ##### SETTINGS


// Begin AutoGenerated Screens - DO NOT EDIT BELOW
void showApp(int page) {
    if ((Screen) page != curScreen) {
        form[curScreen].removeBar();    //remove old StatusBar before proceeding
    }

    switch (page)
    {
		case SCR_HOME:
        {
            //Draw screen UI
            curScreen = (Screen) page;
            form[curScreen].init(screen[curScreen]);  //now defining screen items
            form[curScreen].createBar(barTask, lv_update_task);
            form[curScreen].setTime(gplm.getTime());

			form[curScreen].createLabel(0, -37, "Hello World");    //show element

			form[curScreen].createButton(0, 67, "Button", btn_event_handler, true, 214);    //show element

            form[curScreen].showScreen(ANIM_NONE);   //show the screen w/ no animation
        }
        break;

		case SCR_WATCH:
        {
            //Draw screen UI
            curScreen = (Screen) page;
            form[curScreen].init(screen[curScreen]);  //now defining screen items
            form[curScreen].createBar(barTask, lv_update_task);
            form[curScreen].setTime(gplm.getTime());

			form[curScreen].createLabel(-77, -37, "Hello World");    //show element (tempo)

			form[curScreen].createLabel(0, -37, "Hello World");    //show element (is printing)

			form[curScreen].createLabel(77, -37, "Hello World");    //show element (print percent/ time)

			form[curScreen].createButton(-58, 67, "Button", btn_event_handler, true, 98);    //show element

			form[curScreen].createButton(58, 67, "HomeXY", btn_event_handler, true, 98);    //show element

            form[curScreen].showScreen(ANIM_NONE);   //show the screen w/ no animation
        }
        break;


        default: break;
    }
}
// End AutoGenerated Screens - DO NOT EDIT ABOVE

void setup() {
	Serial.begin(115200);

    wifiStart();
    
    // Begin AutoGenerated Setup - DO NOT EDIT BELOW
	gplm.begin();
	delay(100);
	gplm.listenEvents(false);    //starts listening for events

	device = gplm.wearable; //gives control to the developer to run device methods
	device->lvgl_begin();   //Initiate LVGL core
	device->bl->adjust(120);    //Lower the brightness
	power = gplm.power;		//gives control to the developer to access power methods
	power->setChargeControlCur(500);    //enable fast charging

	showApp(curScreen);
	// End AutoGenerated Setup - DO NOT EDIT ABOVE
}

void loop() {
	Serial.println("Hello World");
	delay(1000);
	
    // Begin AutoGenerated Loop - DO NOT EDIT BELOW
	lv_task_handler();
	delay(50);
	// End AutoGenerated Loop - DO NOT EDIT ABOVE

    // Calls /api/printer?exclude=sd every 6 seconds. [interval(ms)]
    unsigned long currentMillis = millis();
    if(currentMillis - previousMillis > interval) {
    //if(isOnline() && currentMillis - previousMillis > interval) { // make sure that the app is connected
    previousMillis = currentMillis;   
    // Do something... 
    getPrinterState();
    }

}





/*
  ESPOctoClient v0.1   - @kosso : Jan 28, 2018
  --------------------------------------------

  A basic Wifi client to connect to a local OctoPrint system running on a Raspberry Pi 
  and make requests to the OctoPrint REST API.

  See API docs: http://docs.octoprint.org/en/master/api/

  Some test request exmaple methods are down at the bottom of the sketch.
 
 */







void wifiStart(){
    // Connect to WiFi
    WiFi.begin(ssid, password);
    while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print("."); //label
    }
    Serial.println(""); //label
    Serial.println("WiFi connected"); //label

    // Print the IP address
    IPAddress ip = WiFi.localIP(); // prob not needed

    ipStr = String(ip[0]) + '.' + String(ip[1]) + '.' + String(ip[2]) + '.' + String(ip[3]);

    Serial.println("Ready..."); //label
    Serial.println("IP: " + ipStr);  //label
}

////////////////////////////////////////////////////////////////////////// end setup()

//////////////////////////////////////////////////////////////////////////////////////

/* OLD LOOP
void loop() {
  
  // Listen for a button push
  int reading = digitalRead(buttonPin); //(this will be a UI button not an irl button)
  if (reading != lastButtonState) {
    lastDebounceTime = millis();
  }
  

  
  if ((millis() - lastDebounceTime) > debounceDelay) {
    if (reading != buttonState) {
      buttonState = reading;
      if (buttonState == LOW) {//btn
        Serial.println("BUTTON PRESSED! GO HOME XY");
        // getPrinterState(); 
        // getTemperatures();
        goHomeXY();
        // goHomeXYZ();
        // goForLevel();
        
      }
    }
  }
  

  // lastButtonState = reading;


}
*/
//////////////////////////////////////////////////////////////////////////////// end loop()

// Methods 

boolean isOnline(){ // WTF DOES THIS DO??
  if (WiFi.status() != WL_CONNECTED) { // ok this says not conneted to wifi butt whats it used for?
    return false;
  } else {
    return true;
  }
}

// DONT TOUCH !!!!
void parsePrinterStateJSON(String jsonStr){
  DynamicJsonBuffer  jsonBuffer( jsonStr.length() );
  char *json_c_str = &jsonStr[0u];
  JsonObject& root = jsonBuffer.parseObject(json_c_str);
  if (!root.success()) {
    Serial.println("parseJSON() failed"); //label
    return;
  }

  const char* printer_state_text = root["state"]["text"];
  double printer_temperature_bed = root["temperature"]["bed"]["actual"];
  double printer_temperature_bed_target = root["temperature"]["bed"]["target"];
  double printer_temperature_tool0 = root["temperature"]["tool0"]["actual"];
  double printer_temperature_tool0_target = root["temperature"]["tool0"]["target"];

  boolean is_printing = root["state"]["flags"]["printing"];
  boolean is_ready = root["state"]["flags"]["ready"];
  boolean is_paused = root["state"]["flags"]["paused"];
  boolean is_operational = root["state"]["flags"]["operational"];
  boolean has_error = root["state"]["flags"]["error"];
  
  Serial.print("printer_state_text: ");
  Serial.println(printer_state_text);
  
  Serial.print("printer_temperature_bed: ");
  Serial.println(printer_temperature_bed);
  Serial.print("printer_temperature_bed_target: ");
  Serial.println(printer_temperature_bed_target);
  Serial.print("printer_temperature_tool0: ");
  Serial.println(printer_temperature_tool0);
  Serial.print("printer_temperature_tool0_target: ");
  Serial.println(printer_temperature_tool0_target);

  String status_text = ""; // all of this should be a string
  if(is_ready){
    status_text = "PRINTER READY";
  }
  if(is_printing){
    status_text = "PRINTING...";
  }
  if(is_paused){
    status_text = "PAUSED";
  }
  if(has_error){
    status_text = "ERROR!!!!!!";
    // probably do something like stop...
     
  }
  Serial.println("status_text: " + status_text);

  if(is_printing){
     getCurrentJobStatus();
  }

  // set some UI... 
  
}

// DONT TOUCH !!!!
void parseJobJSON(String jsonStr){
  DynamicJsonBuffer  jsonBuffer( jsonStr.length() );
  char *json_c_str = &jsonStr[0u];
  JsonObject& root = jsonBuffer.parseObject(json_c_str);
  if (!root.success()) {
    Serial.println("parseJSON() failed");
    return;
  }

  const char* printer_job_name = root["job"]["file"]["name"];
  double printer_job_progress = root["progress"]["completion"];

  Serial.print("printer_job_name: ");
  Serial.println(printer_job_name);
  Serial.print("printer_job_progress: ");
  Serial.println(printer_job_progress);
  
  // set some UI... 
}


// DONT TOUCH !!!!
String octoRequest(String uri, String method, String postData = ""){
  // HTTPClient request helper
  IPAddress addr;
  addr.fromString(OCTO_HOST);
  
  Serial.println("\nConnecting to OctoPrint server...");  
  if (!client.connect(addr, OCTO_PORT)){
    Serial.println("octoRequest Connection failed!");
    return "";
  } else {
    Serial.println("Connected to server!");
    
    client.println(method + " "+uri+" HTTP/1.1");
    client.println("Host: " + OCTO_HOST);
    client.println("Cache-Control: no-cache");
    client.println("X-Api-Key: " + OCTO_API_KEY);
    if(method=="POST"){
      Serial.println("postData JSON: "+postData);
      client.println("Content-Type: application/json");
      client.print("Content-Length: ");
      client.println(postData.length());
    }
    client.println("");
    if(method=="POST"){
      client.println(postData);
    }
    client.println("");
    while (client.connected()) {
      String line = client.readStringUntil('\n');
      // Serial.println("> "+line);   
      if (line == "\r") {
        // Serial.println("headers received");
        break;
      }
    }
    String response;
    while (client.available()) {
      response = client.readString();
    }
    client.stop();
    return response;    
  }
}

// into a label
void getPrinterState(){
  Serial.println("getPrinterStatus");
  String json = octoRequest("/api/printer?exclude=sd", "GET");
  // Serial.print("STATUS: length: ");
  // Serial.println(json.length()); // test this to make sure we give the DynamicJsonBuffer enough
  // Serial.println(json);
  parsePrinterStateJSON(json);
  
}

// into a label
void getCurrentJobStatus(){
  Serial.println("getCurrentJobStatus");
  String json = octoRequest("/api/job", "GET");
  // Serial.println(json);
  parseJobJSON(json);
}

// into a label
void getTemperatures(){
  Serial.println("getTemperatures");
  String json = octoRequest("/api/printer?exclude=sd,state", "GET");
  // Serial.println("TEMPS: ");
  Serial.println(json);
  = json
  // parse the json and do something...
}


// Some basic G-Code commands.
void goHomeX(){
  String jsonCMD = "{\"commands\":[\"G91\",\"G28 X0\",\"G90\",\"M18\"]}";
  String json = octoRequest("/api/printer/command", "POST", jsonCMD);
}
void goHomeY(){
  String jsonCMD = "{\"commands\":[\"G91\",\"G28 Y0\",\"G90\",\"M18\"]}";
  String json = octoRequest("/api/printer/command", "POST", jsonCMD);
}
void goHomeZ(){
  String jsonCMD = "{\"commands\":[\"G91\",\"G28 Z0\",\"G90\",\"M18\"]}";
  String json = octoRequest("/api/printer/command", "POST", jsonCMD);
}

void goHomeXY(){
  Serial.println("goHomeXY");
  // using printhead method
  //String jsonCMD = "{\"command\":\"home\",\"axes\":[\"x\",\"y\"]}";
  //String json = octoRequest("/api/printer/printhead", "POST", jsonCMD);
  // Direct G-code : Home X and Y
  String jsonCMD = "{\"commands\":[\"G91\",\"G28 X0 Y0\",\"G90\",\"M18\"]}";
  String json = octoRequest("/api/printer/command", "POST", jsonCMD);
}

void goHomeXYZ(){
  Serial.println("goHomeXYZ");
  // Direct G-code : Home X, Y and Z
  String jsonCMD = "{\"commands\":[\"G91\",\"G28 X0 Y0\",\"G28 Z0\",\"G90\",\"M18\"]}";
  String json = octoRequest("/api/printer/command", "POST", jsonCMD);
}

void goForLevel(){
  Serial.println("goForLevel");
  // Homes X & Y, then travels to 60,60. Homes Z then disbales motors. 
  String jsonCMD = "{\"commands\":[\"G91\",\"G28 X0 Y0\",\"G90\",\"G1 X60.0 Y60.0 F3000\",\"G28 Z0\",\"M18\"]}";
  String json = octoRequest("/api/printer/command", "POST", jsonCMD);
}


// Done.
// That's it... Now go and add a screen or something! ;) 

// Cheers!  @kosso : 2018.

